title: Profefonso Blog
email: alfonso@example.com
description: >-
  Explorando el futuro del desarrollo. Un espacio para compartir reflexiones, 
  tutoriales y experimentos tecnológicos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://profefonso.github.io"

# Build settings
theme: null # We are using a custom design
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
