title: Mariana's Blog
email: alfonso@example.com
description: >-
  Exploring the future of development. A space for sharing reflections, 
  tutorials, and technological experiments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://profefonso.github.io"

# Build settings
theme: null # We are using a custom design
lang: en
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
